apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-vol
  labels:
    app: wp
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/new"