apiVersion: v1
kind: Service
metadata:
  name: wp-service
  labels:
    app: wp
spec:
  selector:
    app: wp
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30002
     protocol: TCP